version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y wget unzip
      - wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
      - tar -xf apache-jmeter-5.4.1.tgz
  build:
    commands:
      - cd apache-jmeter-5.4.1/bin
      - ./jmeter -n -t awsdistributed.jmx -l testresult.jtl
  post_build:
    commands:
      - echo "JMeter test execution completed"
