
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing JMeter...
      - wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.5.tgz
      - tar -xzf apache-jmeter-5.5.tgz
      - export PATH=$PATH:$(pwd)/apache-jmeter-5.5/bin
  build:
    commands:
      - echo Running JMeter tests...
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - jmeter -n -t awsdistributed.jmx -l results_${TIMESTAMP}.jtl
  post_build:
    commands:
      - echo JMeter tests completed.
