version: 0.2
 
phases:
  install:
    commands:
      - npm install -g artillery@latest
  pre_build:
    commands:
      - mkdir reports
  build:
    commands:
      - DEBUG=http:response artillery run --output reports/report.json loadtest.yaml
  post_build:
    commands:
      - DEBUG=http:response artillery report --output reports/report reports/report.json
 
artifacts:
  files:
    - "reports/*"
  name: artifacts/$CODEBUILD_BUILD_NUMBER
